name = "webauthn-dev"
main = "cloudflare.ts"
compatibility_date = "2022-06-06"
compatibility_flags = ["streams_enable_constructors"]
account_id = 'efb289061241436254219b424fcea4cf'
kv_namespaces = [ 
  { binding = "KV_STORAGE", id = "93fb8e6b15c14a66a9df18fac1f62c35", preview_id = "61f33c2f08c64296ae099a25d743c9f4" }
]
[vars]
  DEFAULT_KV_NAMESPACE = "KV_STORAGE"
  WORKER_LOCATION = 'http://localhost:8787'

[env.production]
name = "webauthn"
kv_namespaces = [ 
  { binding = "KV_STORAGE", id = "93fb8e6b15c14a66a9df18fac1f62c35", preview_id = "61f33c2f08c64296ae099a25d743c9f4" }
]
[env.production.vars]
  DEFAULT_KV_NAMESPACE = "KV_STORAGE"
  WORKER_LOCATION = 'https://webauthn.qwtel.workers.dev'